## **Saba Junaid**
1. DataFrame()
2. dropna()
3. str.contains()
4. read_json()
5. melt()
6. insert()
7. at[]
8. last()
9. pct_change()
10. to_stata()

## 1. **DataFrame()**
Definition

A DataFrame is a two-dimensional labeled data structure in pandas that stores data in the form of rows and columns, similar to an Excel spreadsheet or a database table.

A DataFrame can contain different types of data in different columns, such as:

* integers
* floating-point numbers
* strings
* dates
* Boolean values
It is one of the most important objects in pandas because almost every data analysis task starts with creating or loading a DataFrame.

# Why do we use DataFrame()?

We use DataFrame() when we want to:


*   DataFrame() is used to convert raw data into a tabular structure (rows and columns)
*   Convert existing data structures like lists, dictionaries, arrays, or files into a pandas table.

*   Perform operations like filtering, cleaning, visualization, and statistical analysis.

* Without a DataFrame, pandas functions cannot be applied efficiently.

In [2]:
import pandas as pd
# pd is (short name) for pandas

# Creating DataFrame from a Dictionary
creating data from dict is common because data is already organized as columns

Real-life Example

Student records.

In [3]:

data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0    Ali   20     85
1   Sara   21     90
2  Ahmed   19     78

In [ ]:
# The dictionary keys become column names
# The dictionary values become column values.
# pd.DataFrame(data)

"""converts the dictionary into a table."""

# Creating DataFrame from a List of Lists
Why use it?

When data comes row by row.

Real-life Example

Exam attendance records.

In [9]:
# Each inner list represents one row.

data = [
    ["Ali", 20],
    ["Sara", 21],
    ["Ahmed", 19]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

    Name  Age
0    Ali   20
1   Sara   21
2  Ahmed   19

# Creating DataFrame from a List of Dictionaries
Why use it?

Very common when data comes from APIs and JSON files.

Real-life Example

Employee records.

In [10]:
data = [
    {"Name":"Ali","Salary":50000},
    {"Name":"Sara","Salary":60000},
    {"Name":"Ahmed","Salary":55000}
]

df = pd.DataFrame(data)
print(df)

    Name  Salary
0    Ali   50000
1   Sara   60000
2  Ahmed   55000

# Creating DataFrame from NumPy Array
Why use it?

Scientific and mathematical datasets often exist as arrays.

Real-life Example

Temperature observations

In [11]:
import pandas as pd
import numpy as np

arr = np.array([
    [25,30],
    [27,32],
    [29,35]
])

df = pd.DataFrame(arr, columns=["Morning","Afternoon"])
print(df)

   Morning  Afternoon
0       25         30
1       27         32
2       29         35

In [12]:
# dataframe can be created using csv file, excel file, jason file

In [ ]:
"""pd.DataFrame(
data=None,
index=None,
columns=None,
dtype=None,
copy=False)"""

| Parameter | Explanation                                                                                            |
| --------- | ------------------------------------------------------------------------------------------------------ |
| `data`    | The actual data used to create the DataFrame (list, dictionary, NumPy array, another DataFrame, etc.). |
| `index`   | Specifies custom row labels for the DataFrame.                                                         |
| `columns` | Specifies column names or selects which columns to include.                                            |
| `dtype`   | Forces all values to be stored as a specific data type (e.g., `int`, `float`, `str`).                  |
| `copy`    | If `True`, creates a separate copy of the data instead of linking to the original data.                |

## **2. dropna()**
Definition

dropna() is a pandas function used to remove missing values (NaN values) from a DataFrame or Series.

Missing values occur when data is unavailable, incomplete, or not recorded

## Why do we use dropna()?

*   Missing values can affect analysis.
*   We want only complete records.

*   Statistical calculations require complete data.

*   Machine learning models cannot accept missing values

In [5]:
data={
"Name":["Ali","Sara","Ahmed"],
"Marks":[90,None,80],
"Age":[20,21,None]
}

df=pd.DataFrame(data)

print(df)

    Name  Marks   Age
0    Ali   90.0  20.0
1   Sara    NaN  21.0
2  Ahmed   80.0   NaN

In [6]:
df.dropna()
# Rows containing any missing value are removed.

  Name  Marks   Age
0  Ali   90.0  20.0

In [ ]:
# syntax of dropna()
"""DataFrame.dropna(
axis=0,
how='any',
thresh=None,
subset=None,
inplace=False
)"""

Parameters of dropna()

 # 1. axis

Defines whether we remove rows or columns.

 **df.dropna(axis=0)**
(Default)

Removes rows.

Example:

df.dropna(axis=0) this will remove any row containing misssing value

# axis=1
Removes columns containing missing values.

Example:

**df.dropna(axis=1)**

Output:

Name
Ali
Sara
Ahmed

Columns with NaN are removed.

# 2. how

Controls when deletion happens.

how="any"

(Default)

Remove if any missing value exists.

**df.dropna(how="any")**

# how="all"

Remove only when all values are missing.

Example:

A	B
NaN	NaN
2	3

Only first row removed.

# 3. thresh

Defines minimum number of non-null values required.

Example:

**df.dropna(thresh=2)**

Meaning:

Keep rows having at least 2 valid values.

# 4. subset

Checks missing values only in specific columns.

Example:

**df.dropna(subset=["Marks"])**

Only rows with missing Marks are removed.

# 5. inplace

Controls whether changes are permanent.

inplace=False

(Default)

Creates a new DataFrame.

**new_df=df.dropna()**

Original remains unchanged.

## inplace=True

Changes original DataFrame.

**df.dropna(inplace=True)**

## Alternatives of dropna()
# 1. fillna()

Instead of deleting missing data, replace it.

Example:

**df.fillna(0)**

Output:

Missing values become zero.

# 2. replace()

Replace specific values.

**df.replace("NA",0)**

# 3. interpolate()

Estimate missing values mathematically.

Example:

**df.interpolate()**

Used mostly for:

time series data
sensor data

# dropna() Advantages
1. Simple and fast.
2. Removes incomplete records.
3. Useful before machine learning.

# dropna() Disadvantages
1. Can remove important information.
2. Large deletion can reduce dataset size.
3. Not suitable when missing values have meaning

##  **3. str.contains()**

## What is str.contains()?

str.contains() is a pandas string method used to check whether a particular text pattern exists inside strings of a Series (usually a DataFrame column).

It returns True if the pattern is found and False if it is not found.

## Why is str.contains() needed?

Suppose you have 100,000 records.

You want to find:

* All students whose names contain "Ali"
* All emails containing "@gmail.com"
* All products containing "Laptop"
* All cities containing "Lahore"

Checking manually is impossible.

str.contains() automatically searches every row and tells us where the pattern exists.

# What problem does it solve?

Without str.contains():

**for value in column:**
    
    # manually search text


This is slow and complicated.

str.contains() performs vectorized searching on the entire column at once.

In [14]:
# Real-life Example 1: Student Names

students = pd.DataFrame({
    "Name": ["Ali Ahmed", "Sara Khan", "Ali Raza", "Ayesha"]
})

print(students)

        Name
0  Ali Ahmed
1  Sara Khan
2   Ali Raza
3     Ayesha

In [17]:
## Find names containing "Ali"
students["Name"].str.contains("Ali")

# We want to identify rows containing "Ali".

#  True means found.

# False means not found.

0     True
1    False
2     True
3    False
Name: Name, dtype: bool

In [19]:
# for filtering Rows Usually we use:

students[
    students["Name"].str.contains("Ali")
]

        Name
0  Ali Ahmed
2   Ali Raza

In [20]:
# Email Analysis

emails = pd.DataFrame({
    "Email":[
        "ali@gmail.com",
        "sara@yahoo.com",
        "ahmed@gmail.com"
    ]
})

In [22]:
# Find Gmail users:

emails[
emails["Email"].str.contains("@gmail")
]

             Email
0    ali@gmail.com
2  ahmed@gmail.com

Why is this useful?

Companies often separate customers based on:

* Email providers
* Domains
* Countries
* Product categories

In [ ]:
"""Series.str.contains(
pat,
case=True,
flags=0,
na=None,
regex=True
)"""

| Parameter | Explanation                                                                                                                                                         |
| --------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `pat`     | The text or pattern you want to search for inside strings. Without a search pattern, Pandas does not know what to find.                                             |
| `case`    | Controls case sensitivity. If `True`, the search is case-sensitive; if `False`, it ignores uppercase/lowercase differences.                                         |
| `flags`   | Used when working with advanced regular expression (regex) patterns. It allows the use of regular expression flags (e.g., `IGNORECASE` to ignore capitalization).   |
| `na`      | Defines what to return for missing values (`NaN`). Without it, missing values may create errors or unwanted `NaN` results.                                          |
| `regex`   | Determines whether the pattern is treated as a regular expression. If `True`, `pat` is interpreted as a regex pattern; if `False`, it searches for exact text only. |

## Regex
(Regular Expression) is a special pattern used to search, match, or filter text.

| Regex   | Meaning              | Matches    |
| ------- | -------------------- | ---------- |
| `"Ali"` | Contains Ali         | Ali Ahmed  |
| `"^A"`  | Starts with A        | Ali, Ahmed |
| `"a$"`  | Ends with a          | Sara       |
| `"\d"`  | Contains a number    | Ali123     |
| `"."`   | Any single character | A, B, 5, @ |

# Alternatives to str.contains()

In [23]:
# Python "in" operator
"Ali" in "Ali Ahmed"

True

# Why not use it?

Works for one value only.

Cannot efficiently search an entire column.

In [26]:

# Create DataFrame
df = pd.DataFrame({
    "Name": ["Ali Khan", "Sara Ahmed", "Ali Raza", "Zara"]
})

# Apply function to check if "Ali" exists in Name column
df["Name"].apply(
    lambda x: "Ali" in x
)

0     True
1    False
2     True
3    False
Name: Name, dtype: bool

# Advantages of str.contains()
* Fast
* Optimized for pandas.
* Searches entire column
* No loops required.
* Supports regex
* Very powerful.
* Easy filtering
* Can directly select rows.

# Disadvantages
* Only for strings
* Numeric columns require conversion.

Example:

**df["Age"].astype(str)**

When should we use str.contains()?

Use when:

* Searching names

* Searching emails

* Finding keywords

* Text classification

* Product filtering

* Log analysis

# When should we NOT use it?

Avoid when:

* Data is purely numeric

* Exact equality comparison is needed

# **3. read_json() in Pandas**

## What is read_json()?

read_json() is a pandas function used to read data stored in JSON (JavaScript Object Notation) format and convert it into a DataFrame.

It allows pandas to work with JSON data for analysis.

# Why is read_json() needed?

Many modern applications, websites, and APIs do not provide data in CSV or Excel format. They commonly provide data in JSON format.
Common places where JSON data is used:

* Web APIs (fetching data from websites)
* Mobile applications
* Databases
* Data exchange between software systems
* Weather apps receive weather information as JSON.
* Social media APIs provide posts and user information as JSON.

In [27]:
# What is JSON?
{
 "Name": "Ali",
 "Age": 20,
 "City": "Lahore"
}

# It stores information using key-value pairs.

# Key → Column name
# Value → Data

{'Name': 'Ali', 'Age': 20, 'City': 'Lahore'}

# Real-life Example: Employee Data

In [30]:
# JSON file
[
 {
  "Name":"Ali",
  "Department":"IT",
  "Salary":50000
 },
 {
  "Name":"Sara",
  "Department":"HR",
  "Salary":60000
 }
]

# Save this data in a file named employees.json because
# JSON data must be saved as a separate .json file before using pd.read_json("employees.json")

[{'Name': 'Ali', 'Department': 'IT', 'Salary': 50000},
 {'Name': 'Sara', 'Department': 'HR', 'Salary': 60000}]

In [31]:
# df = pd.read_json("employees.json")

# print(df)

# If you want to run everything in one Python file

In [33]:
# pd.read_json() reads a JSON file or JSON string;
# it does not directly read a Python list written outside a file

In [32]:
import pandas as pd
import json

data = [
    {
        "Name": "Ali",
        "Department": "IT",
        "Salary": 50000
    },
    {
        "Name": "Sara",
        "Department": "HR",
        "Salary": 60000
    }
]

# Convert Python data into JSON file
with open("employees.json", "w") as file:
    json.dump(data, file)

# Read JSON using Pandas
df = pd.read_json("employees.json")

print(df)

   Name Department  Salary
0   Ali         IT   50000
1  Sara         HR   60000

# Why use this method?

Because the data is already available in JSON format. Instead of manually converting it, pandas directly creates a DataFrame.

In [ ]:
"""pd.read_json(
path,
orient=None,
typ='frame',
dtype=None,
convert_dates=True
)"""

| Parameter          | Explanation                                                                                  | Why Needed?                                                                                                                                                         | Example                                                       |
| ------------------ | -------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| `path`             | Specifies the location of the JSON file, URL, or JSON data that Pandas needs to read.        | Pandas needs to know where the data is stored before it can load it into a DataFrame.                                                                               | `python pd.read_json("data.json") `                           |
| `orient`           | Defines the structure or layout of JSON data so Pandas knows how to interpret it correctly.  | Different applications store JSON data in different formats. `orient` tells Pandas how the JSON structure is organized.                                             | `python pd.read_json("data.json", orient="records") `         |
| `orient="records"` | Each JSON object represents one row of the DataFrame. This is the most commonly used format. | Useful when JSON data is stored as a list of records (rows).                                                                                                        | `json [ {"Name":"Ali","Age":20}, {"Name":"Sara","Age":21} ] ` |
| `orient="columns"` | Data is arranged by column names, where each column contains its values.                     | Used when JSON is organized column-wise.                                                                                                                            | `json {"Name":{"0":"Ali"}, "Age":{"0":20}} `                  |
| `orient="index"`   | Data is arranged by row index, where each index contains a complete row.                     | Used when JSON stores data according to row labels/index values.                                                                                                    | `json {"0":{"Name":"Ali","Age":20}} `                         |
| `dtype`            | Controls the data types of columns when reading JSON data.                                   | Pandas may automatically convert data types. This parameter allows control over whether conversion should happen.                                                   | `python pd.read_json("data.json", dtype=False) `              |
| `convert_dates`    | Converts date values from text format into Pandas datetime format.                           | Date values stored as strings cannot be easily analyzed. Converting them allows sorting by date, calculating time differences, and performing time-series analysis. | `python pd.read_json("sales.json", convert_dates=True) `      |

## Alternative Methods
**1. read_csv()**

Used when data is CSV format.

Example:

**pd.read_csv("data.csv")**

**2. read_excel()**

Used for Excel files.

Example:

**pd.read_excel("data.xlsx")**

When should we use read_json()?

Use when:

* Data comes from APIs

* Data is stored as JSON files

* Working with web applications

* Handling nested data

## Advantages
* Directly converts JSON to DataFrame.
* Saves time.
* Works well with web data.
* Handles different JSON structures

# Limitations
* Complex nested JSON may require additional processing.
* Large JSON files can consume memory.
* Incorrect structure may produce errors.

## **4. melt() in Pandas**

## What is melt()?

melt() is a pandas function used to convert wide-format data into long-format data.

It reshapes a DataFrame by turning columns into rows.

## Why is melt() needed?

Many datasets are stored in a wide format because humans find them easy to read.

Example:
| Student | Math | English | Science |
| ------- | ---- | ------- | ------- |
| Ali     | 80   | 75      | 90      |
| Sara    | 85   | 88      | 92      |

But statistical analysis and visualization often require long format:

| Student | Subject | Marks |
| ------- | ------- | ----- |
| Ali     | Math    | 80    |
| Ali     | English | 75    |
| Ali     | Science | 90    |

## Real-life Example: Student Marks

In [35]:
df = pd.DataFrame({
"Student":["Ali","Sara"],
"Math":[80,85],
"English":[75,88],
"Science":[90,92]
})

print(df)

  Student  Math  English  Science
0     Ali    80       75       90
1    Sara    85       88       92

In [36]:
# Applying melt()
long_df = pd.melt(
df,
id_vars=["Student"],
value_vars=["Math","English","Science"],
var_name="Subject",
value_name="Marks"
)

print(long_df)

  Student  Subject  Marks
0     Ali     Math     80
1    Sara     Math     85
2     Ali  English     75
3    Sara  English     88
4     Ali  Science     90
5    Sara  Science     92

# Why use melt() here?

Because subjects were stored as separate columns. We converted them into one Subject column, making analysis easier.

In [ ]:
"""pd.melt(
frame,
id_vars,
value_vars,
var_name,
value_name
)"""

| Parameter    | Explanation                                                                                   | Why Needed?                                                                                                                    | Example                                 |
| ------------ | --------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------ | --------------------------------------- |
| `frame`      | The DataFrame that you want to reshape from wide format to long format.                       | Pandas needs to know which DataFrame should be transformed.                                                                    | `python pd.melt(df) `                   |
| `id_vars`    | Columns that should remain unchanged during transformation. These columns act as identifiers. | We use it because some columns contain important information (like Student ID or Name) that should not be converted into rows. | `python id_vars=["Student"] `           |
| `value_vars` | Columns that will be converted from columns into rows.                                        | It tells Pandas which columns need to be reshaped. If not provided, all columns are melted except `id_vars`.                   | `python value_vars=["Math","English"] ` |
| `var_name`   | New name given to the column that contains the original column names after melting.           | It makes the reshaped data easier to understand by replacing the default column name `"variable"`.                             | `python var_name="Subject" `            |
| `value_name` | New name given to the column that contains the values from the original columns.              | It replaces the default name `"value"` and gives a meaningful name to the data values.                                         | `python value_name="Marks" `            |

## **Alternatives of melt()**
**1. pivot()**

Opposite operation.

Converts long format into wide format.

**2. stack()**

Moves columns into index.

**3. wide_to_long()**

Specialized reshaping function.

## When to use melt()

Use when:

* Preparing data for visualization

* Working with statistical models

* Creating tidy datasets

* Comparing multiple variables

**Advantages**
* Makes data analysis easier.
* Creates tidy format.
* Works well with visualization libraries.

**Limitations**

*Can increase number of rows significantly.
* Wrong selection of columns can produce incorrect results.

## **6. insert() in Pandas**

## What is insert()?

insert() is a pandas DataFrame method used to add a new column at a specific position in a DataFrame.

Unlike normal column assignment, which always adds a column at the end, insert() allows us to decide exactly where the new column should appear.

## Why is insert() needed?

Suppose you have an employee dataset:
| Name | Salary |
| ---- | ------ |
| Ali  | 50000  |
| Sara | 60000  |

Now you want to add Department between Name and Salary:

Desired:

| Name | Department | Salary |
| ---- | ---------- | ------ |
| Ali  | IT         | 50000  |

## If we use:

df["Department"] = ["IT","HR"]
The new column will automatically appear at the end:

Name	Salary	Department
Ali	50000	IT

This may not be suitable for reports.

insert() solves this problem by allowing controlled column placement.

## Real-life Example

A company has employee data.

Initially:

**Employee_ID | Name | Salary**

After collecting new information, we want:

**Employee_ID | Name | Department | Salary**

The Department column should be placed before Salary.

## Purpose of insert()

The main purposes are:

* Adding a new column.
* Controlling column order.
* Preparing datasets for reports and analysis.
* Organizing data in a meaningful structure.

In [ ]:
"""Syntax
DataFrame.insert(
    loc,
    column,
    value,
    allow_duplicates=False
)"""

| Parameter          | Explanation                                                                                                 | Why Needed?                                                                                                                                 |
| ------------------ | ----------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------- |
| `loc`              | Defines the position (index number) where the new column will be inserted. Column positions start from `0`. | Pandas needs to know where the new column should appear in the DataFrame.                                                                   |
| `column`           | Specifies the name of the new column that will be created.                                                  | Every column needs a label/name so it can be accessed and identified later.                                                                 |
| `value`            | Contains the data that will be stored in the new column.                                                    | Without values, Pandas cannot create and fill the new column.                                                                               |
| `allow_duplicates` | Controls whether duplicate column names are allowed. The default value is `False`.                          | It prevents accidentally creating columns with the same name. Set it to `True` only when duplicate column names are intentionally required. |

## **Alternative Methods**
**1. Direct assignment**
df["Age"]=[20,21]

# Why use it?

When column position does not matter.

##**Limitation:**

Always adds column at the end.

**2. concat()**
pd.concat([df,new_column],axis=1)

## Why use it?

Useful when combining complete DataFrames.

## Advantages of insert()
* Gives control over column position.
* Makes reports organized.
* Easy to understand.
## Limitations
* Cannot insert multiple columns at once easily.
* Duplicate columns can create confusion.
* Position must be calculated manually.

**7. at[] in Pandas**

## What is at[]?

at[] is a pandas accessor used to access or modify a single value in a DataFrame using row and column labels.

It is designed specifically for fast single-cell operations.

## Why is at[] needed?

Sometimes we do not want to select an entire row or column. We only need one specific value.

Example:

A student's marks were entered incorrectly.

Original:

| Name | Marks |
| ---- | ----- |
| Ali  | 80    |


Need to change only Ali's marks to 90.

Using normal selection methods is unnecessary.

at[] directly targets that cell.

## Purpose of at[]
* Reading one value.
* Updating one value.
* Fast single-cell access.

## Real-life Example

Updating one customer's phone number in a database.

In [37]:
# Syntax
# DataFrame.at[row_label, column_label]

In [38]:
import pandas as pd

students=pd.DataFrame({
"Name":["Ali","Sara"],
"Marks":[80,90]
})

print(students)

   Name  Marks
0   Ali     80
1  Sara     90

In [39]:
# Accessing a value
students.at[0,"Marks"]

np.int64(80)

In [40]:
# Modifying a value
students.at[0,"Marks"]=95

print(students)

   Name  Marks
0   Ali     95
1  Sara     90

## Why use at() instead of loc()?

Both can access values.

Example:

**df.loc[0,"Marks"]**

also works.

But:

at[] → optimized for one value.

loc[] → designed for selecting multiple rows and columns.

# **Alternatives**
# 1. loc[]

Used for label-based selection.

Example:

df.loc[0,"Marks"]

# **2. iloc[]**

Used for position-based selection.

Example:

**df.iloc[0,1]**

## **Advantages**
* Faster for single value operations.
* Simple syntax.
* Prevents unnecessary selection.
## **Limitations**
* Cannot select multiple rows.
* Cannot select multiple columns.
* Requires labels.

## **8. last() in Pandas**

## What is last()?

last() is a pandas DataFrame method used to select the last time period of data from a time-series DataFrame.

It works with a DataFrame that has a DateTime index.

## Why is last() needed?

In time-series analysis, datasets often contain thousands of records.

Examples:

* Stock prices
* Weather measurements
* Sales records
* Sensor readings

Analysts frequently need recent data.

Instead of manually filtering dates, last() quickly extracts the required recent period.

## Purpose of last()

To retrieve data from the end of a time-based dataset.

## Real-life Example

A company records daily sales
| Date  | Sales |
| ----- | ----- |
| Jan 1 | 500   |
| Jan 2 | 700   |
| Jan 3 | 900   |

Manager wants the last 2 days' sales.

last() retrieves them quickly.

In [41]:
# dataframe

sales=pd.DataFrame({
"Date":pd.date_range(
"2026-01-01",
periods=5
),
"Sales":[100,200,300,400,500]
})

sales=sales.set_index("Date")

print(sales)

            Sales
Date
2026-01-01    100
2026-01-02    200
2026-01-03    300
2026-01-04    400
2026-01-05    500

In [42]:
## Using last()
sales.last("2D")

/tmp/ipykernel_3827/882775027.py:2: FutureWarning: last is deprecated and will be removed in a future version. Please create a mask and filter using `.loc` instead
  sales.last("2D")

            Sales
Date
2026-01-04    400
2026-01-05    500

# **Explanation**

## 2D means:

Last 2 days.

Other examples:

"7D"

Last 7 days.

"3M"

Last 3 months.

## **Important Requirement**

## last() requires:

DateTime index.

Without dates, it will not work correctly.

## **Alternatives**


**1. tail()**

df.tail()
Use:

Gets last rows.

# Difference:

Does not understand time periods.

**2. Date filtering**

Example:

**df[df.index>"2026-01-03"]**

More flexible but longer.

## **Advantages**
* Quick extraction of recent periods.
* Useful in time-series analysis.
* Simple syntax.
## **Limitations**
* Works only with DateTime index.
* Not suitable for normal DataFrames.
* It is deprecated in newer pandas versions; date slicing is preferred.

## **9. pct_change() in Pandas**

## What is pct_change()?

pct_change() is a pandas method used to calculate the percentage change between the current value and the previous value in a Series or DataFrame.

It tells us how much a value has increased or decreased compared with its previous value.

The result is returned as a decimal value.

Example:

If sales increase from 100 to 120:


120−100/100
	​

=0.20

Output:

0.20

which means 20% increase.

## Why is pct_change() needed?

Looking only at actual values does not always show the growth pattern.

Example:

Monthly sales:

| Month    | Sales |
| -------- | ----- |
| January  | 1000  |
| February | 1500  |
| March    | 1800  |


## A manager wants to know:

* How much did sales grow?
* Which month had the highest increase?
* Is growth improving or decreasing?

## The difference alone:

January → February:

1500 - 1000 = 500

does not tell the growth rate.

## Percentage change gives:

50% increase

which is easier to compare.

## **Purpose of pct_change()**

The main purposes are:

* Measuring growth rate.
* Comparing changes over time.
* Financial analysis.
* Sales analysis.
* Economic data analysis.
8 Time-series analysis.

In [43]:
## A company records monthly sales.

sales = pd.DataFrame({
    "Month":["January","February","March","April"],
    "Sales":[1000,1500,1200,1800]
})

print(sales)

      Month  Sales
0   January   1000
1  February   1500
2     March   1200
3     April   1800

In [44]:
# Applying pct_change()
sales["Growth"] = sales["Sales"].pct_change()

print(sales)

      Month  Sales  Growth
0   January   1000     NaN
1  February   1500     0.5
2     March   1200    -0.2
3     April   1800     0.5

## Explanation of Output

**First row:**

NaN

because there is no previous value to compare January with.

**February:**

Previous sales = 1000

Current sales = 1500

Calculation:

(1500-1000)/1000

=0.5

Meaning:

50% increase

**March:**

(1200-1500)/1500

=-0.20

Meaning:

20% decrease

**April:**

(1800-1200)/1200

=0.50

Meaning:

50% increase

## **Converting decimal into percentage**

Normally we multiply by 100:

sales["Growth_percentage"] = (
sales["Sales"].pct_change()*100
)

Output:

50
-20
50

In [ ]:
"""Syntax
DataFrame.pct_change(
periods=1,
fill_method=None,
axis=0
)"""

## **Parameters of pct_change()**
**1. periods**
Meaning:

Defines how many previous values should be used for comparison.

Default:

periods=1

Means compare with the previous row.

Example:

sales["Sales"].pct_change(periods=2)

**Now:**

* March compares with January.

* April compares with February.

**Why is periods needed?**

Sometimes we do not want daily change; we want:

* Weekly change
* Monthly change
* Yearly change

**Real-life example:**

# Stock market:

Daily price change:

periods=1

Yearly growth:

periods=365

**2. fill_method**

Meaning:

Defines how missing values are filled before calculation.

Older pandas versions used:

fill_method="ffill"

which forward-filled missing values.

**Why needed?**

Missing data can affect percentage calculations.

**3. axis**

Meaning:

Determines whether calculation happens across rows or columns.

Default:

axis=0

Calculation is done vertically.

## Example:

| Month | Product A | Product B |
| ----- | --------- | --------- |
| Jan   | 100       | 200       |
| Feb   | 150       | 300       |

Percentage change can be calculated separately for each product.

## **Alternatives of pct_change()**

**1. Manual calculation**

Formula:

(Current - Previous) / Previous

Example:

(sales[1]-sales[0])/sales[0]

**Why not always use it?**

For large datasets it is slow and requires more coding.

**2. diff()**

Example:

sales["Sales"].diff()

## Difference:

diff() gives absolute change.

Example:

1500-1000=500

## pct_change() gives relative change.

Example:

50%
When should we use pct_change()?

Use when:

* Analyzing growth trends

* Comparing performance over time

* Studying financial data

* Measuring percentage increase/decrease

## When should we NOT use it?

Avoid when:

* Values have no meaningful order

Example:

Student names.

* Data is categorical.

## **Advantages**
* Simple calculation.
* Saves coding time.
* Useful for large datasets.
8 Works directly with pandas Series and DataFrames.
## **Limitations**
* First value always becomes NaN.
* Zero previous values can cause problems.
* Does not explain the reason for change.

## **10. to_stata() in Pandas**

**What is to_stata()?**

to_stata() is a pandas method used to export a DataFrame into a Stata data file format (.dta).

It allows data created or cleaned in pandas to be opened and analyzed in Stata software.

**Why is to_stata() needed?**

Different researchers and organizations use different statistical software.

For example:

A data scientist may clean data using Python/pandas.
A statistician may perform statistical analysis using Stata.

They need a way to transfer data between programs.

to_stata() provides this connection.

**What is Stata?**

Stata is a statistical software widely used in:

* Economics
* Public health
* Social sciences
* Research studies

It uses its own file format:

.dta

**Purpose of to_stata()**

The purpose is:

* Export pandas DataFrames.
* Share data with Stata users.
* Maintain data structure during transfer.

In [ ]:
# Real-life Example
# A researcher collects survey data.

Survey data

     ↓

Python/Pandas

     ↓

Cleaning and preparation

     ↓

Stata

     ↓
     
Statistical analysis

In [45]:

research = pd.DataFrame({

"Participant":["Ali","Sara","Ahmed"],

"Age":[25,30,28],

"Score":[80,90,85]

})

print(research)

  Participant  Age  Score
0         Ali   25     80
1        Sara   30     90
2       Ahmed   28     85

In [46]:
# Exporting to Stata
research.to_stata(
"research_data.dta"
)

In [ ]:
"""Output

A file is created:

research_data.dta

This file can be opened in Stata."""

In [ ]:
# Syntax
"""DataFrame.to_stata(
path,
write_index=True,
version=None
)"""

| Parameter     | Explanation                                                                                                                             | Why Needed?                                                                                                                                           |
| ------------- | --------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------- |
| `path`        | Specifies the location and name of the Stata file where the DataFrame will be saved. The file is usually saved with a `.dta` extension. | Pandas needs to know where to store the exported data. Without a path, it cannot create the Stata file.                                               |
| `write_index` | Determines whether the DataFrame index should be written into the Stata file. Default value is `True`.                                  | Controls whether row labels (index values) are included in the exported file. If the index is not useful, it can be removed by setting it to `False`. |
| `version`     | Specifies the version of the Stata file format to create.                                                                               | Different versions of Stata support different features and data sizes. This ensures compatibility with the required Stata software version.           |

## **Alternatives of to_stata()**

**1. to_csv()**

Exports data as CSV.

Example:

**df.to_csv("data.csv")**

## When use?

When data needs to be opened in:

Excel
Many programming languages
General software

**2. to_excel()**

Exports as Excel file.

**df.to_excel("data.xlsx")**

## When use?

For business reports and spreadsheets.

**3. to_json()**

Exports JSON format.

**df.to_json("data.json")**

## When use?

For web applications and APIs.

**Advantages of to_stata()**
* Maintains compatibility with Stata.
* Easy data transfer.
* Useful in research workflows.

**Limitations**

* Only useful for Stata users.
* Some pandas data types may not perfectly match Stata types.
* Requires Stata-compatible formatting.

## When should we use to_stata()?

Use when:

* Collaborating with Stata researchers

* Performing statistical research

* Working with survey datasets

## When should we not use it?

Avoid when:

* Data will only be used in Excel → use to_excel()

* Data is for web applications → use to_json()